import enum
import uuid
import logging
from datetime import datetime
from sqlalchemy.orm import DeclarativeBase, sessionmaker
from sqlalchemy import Column, DateTime, Enum, String, Text, create_engine

from src.config import Settings

logger = logging.getLogger(__name__)

try:
    engine = create_engine(
        url = Settings().database_url,
        connect_args = {
            "check_same_thread": False
        },
        echo = True
    )
    logger.info(f"Database engine created: {Settings().database_url}")

except Exception as error:
    logger.error(f"Failed to create database engine: {error}", exc_info = True)

    raise

try:
    SessionLocal = sessionmaker(
        autocommit = False,
        autoflush = False,
        bind = engine
    )
    logger.info("SessionLocal factory created")

except Exception as error:
    logger.error(f"Failed to create SessionLocal factory: {error}", exc_info = True)

    raise

class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

class DraftStatus(str, enum.Enum):
    """Lifecycle states of a draft reply.

    Values
    ------
    pending  : Freshly generated by the AI agent, awaiting human review.
    approved : User has approved the draft as-is.
    edited   : User has manually modified the draft body.
    rejected : User has discarded the draft.
    sent     : Draft was successfully dispatched via Gmail API.
    failed   : Sending attempt raised an unrecoverable error.
    """

    pending = "pending"
    approved = "approved"
    edited = "edited"
    rejected = "rejected"
    sent = "sent"
    failed = "failed"

class Draft(Base):
    """
    Represents a single AI-generated email reply draft.

    Each row corresponds to one incoming email that the agent has
    processed.  The draft moves through DraftStatus stages as the
    human reviews and eventually sends (or rejects) it.

    Columns
    -------
    id            : UUID primary key (generated at insert time).
    thread_id     : Gmail thread ID – used to keep replies in-thread.
    message_id    : RFC 2822 Message-ID header of the original email.
                    Stored in In-Reply-To / References when sending.
    sender        : "From" address of the original email.
    subject       : Subject of the original email.
    original_body : Plain-text body of the email we are replying to.
    draft_body    : AI-generated reply text.
    status        : Current lifecycle state (see DraftStatus).
    tone          : Tone hint used when generating (formal / friendly …).
    created_at    : UTC timestamp of row creation.
    updated_at    : UTC timestamp of last update.
    """

    __tablename__ = "drafts"

    id: str = Column(String(36), primary_key = True, default = lambda: str(uuid.uuid4()))
    thread_id: str = Column(String(255), nullable = True, index = True)
    message_id: str = Column(String(512), nullable = True)
    sender: str = Column(String(512), nullable = False)
    subject: str = Column(String(1024), nullable = False, default = "(no subject)")
    original_body: str = Column(Text, nullable = False, default = "")
    draft_body: str = Column(Text, nullable = False, default = "")
    status: DraftStatus = Column(
        Enum(DraftStatus), nullable = False, default = DraftStatus.pending, index = True
    )
    tone: str = Column(String(64), nullable = False, default = "formal")
    created_at: datetime = Column(DateTime, default = datetime.utcnow, nullable = False)
    updated_at: datetime = Column(
        DateTime,
        default = datetime.utcnow,
        onupdate = datetime.utcnow,
        nullable = False
    )

    def __repr__(self) -> str:
        return f"<Draft id={self.id!r} subject={self.subject!r} status={self.status}>"

class Log(Base):
    """
    Append-only activity log for every system event.

    Used for monitoring, debugging, and the audit trail displayed
    in the Streamlit UI.

    Columns
    -------
    id        : UUID primary key.
    event     : Short event code, e.g. 'draft_created', 'email_sent'.
    detail    : Human-readable description / additional context.
    timestamp : UTC timestamp of the event.
    """

    __tablename__ = "logs"

    id: str = Column(String(36), primary_key = True, default = lambda: str(uuid.uuid4()))
    event: str = Column(String(128), nullable = False, index = True)
    detail: str = Column(Text, nullable = True, default = "")
    timestamp: datetime = Column(DateTime, default = datetime.utcnow, nullable = False)

    def __repr__(self) -> str:
        return f"<Log event={self.event!r} ts={self.timestamp}>"